version: '3.4'
services:
  base:
    build:
      context: .
      target: gentoo-base
    image: apnpucky/gentoo-base:${TAG:-latest}

  ebuild-ci:
    build:
      context: .
      target: gentoo-ebuild-ci
    image: apnpucky/gentoo-ebuild-ci:${TAG:-latest}

  dev:
    build:
      context: .
      target: gentoo-dev
    image: apnpucky/gentoo-dev:${TAG:-latest}

  hep-forge:
    build:
      context: .
      target: gentoo-hep-forge
    image: apnpucky/gentoo-hep-forge:${TAG:-latest}


  lhapdf-looptools:
    build:
      context: .
      target: gentoo-lhapdf-looptools
    image: apnpucky/gentoo-lhapdf-looptools:${TAG:-latest}

  lhapdf-looptools:
    build:
      context: .
      target: gentoo-lhapdf-looptools
    image: apnpucky/gentoo-lhapdf-looptools:${TAG:-latest}

  rivet3-pythia8-hepmc3:
    build:
      context: .
      target: gentoo-rivet3-pythia8-hepmc3
    image: apnpucky/gentoo-rivet3-pythia8-hepmc3:${TAG:-latest}

  rivet3-pythia8-hepmc2:
    build:
      context: .
      target: gentoo-rivet3-pythia8-hepmc2
    image: apnpucky/gentoo-rivet3-pythia8-hepmc2:${TAG:-latest}

  latex:
    build:
      context: .
      target: gentoo-latex
    image: apnpucky/gentoo-latex:${TAG:-latest}
