version: '3.4'
services:
  base:
    build:
      context: .
      target: base
    image: apnpucky/ubuntu-base:${TAG:-latest}

  dev:
    build:
      context: .
      target: dev
    image: apnpucky/ubuntu-dev:${TAG:-latest}

  apt:
    build:
      context: .
      target: apt
    image: apnpucky/ubuntu-apt:${TAG:-latest}

  pip:
    build:
      context: .
      target: pip
    image: apnpucky/ubuntu-pip:${TAG:-latest}

  poetry:
    build:
      context: .
      target: poetry
    image: apnpucky/ubuntu-poetry:${TAG:-latest}

  python:
    build:
      context: .
      target: python
    image: apnpucky/ubuntu-python:${TAG:-latest}

  python-lhapdf-6.5.4:
    build:
      context: .
      target: python-lhapdf
      args:
        - LHAPDF_VERSION=6.5.4
    image: apnpucky/ubuntu-python-lhapdf:6.5.4-${TAG:-latest}

  python-lhapdf:
    build:
      context: .
      target: python-lhapdf
    image: apnpucky/ubuntu-python-lhapdf:${TAG:-latest}

  python-lhapdf-looptools:
    build:
      context: .
      target: python-lhapdf-looptools
    image: apnpucky/ubuntu-python-lhapdf-looptools:${TAG:-latest}

  python-latexmk:
    build:
      context: .
      target: python-latexmk
    image: apnpucky/ubuntu-python-latexmk:${TAG:-latest}

    
  python-latexmk-form:
    build:
      context: .
      target: python-latexmk-form
    image: apnpucky/ubuntu-python-latexmk-form:${TAG:-latest}
