version: '3.4'
services:
  base:
    build:
      context: .
      target: base
    image: apnpucky/ubuntu-base:${TAG:-latest}

  dev:
    build:
      context: .
      target: dev
    image: apnpucky/ubuntu-dev:${TAG:-latest}

  apt:
    build:
      context: .
      target: apt
    image: apnpucky/ubuntu-apt:${TAG:-latest}

  pip:
    build:
      context: .
      target: pip
    image: apnpucky/ubuntu-pip:${TAG:-latest}

  pip-lhapdf-6.4.0:
    build:
      context: .
      target: pip-lhapdf
      args:
        - LHAPDF_VERSION=6.4.0
    image: apnpucky/ubuntu-pip-lhapdf:6.4.0-${TAG:-latest}

  pip-lhapdf-6.5.3:
    build:
      context: .
      target: pip-lhapdf
      args:
        - LHAPDF_VERSION=6.5.3
    image: apnpucky/ubuntu-pip-lhapdf:6.5.3-${TAG:-latest}

  pip-lhapdf:
    build:
      context: .
      target: pip-lhapdf
    image: apnpucky/ubuntu-pip-lhapdf:${TAG:-latest}

  pip-lhapdf-looptools:
    build:
      context: .
      target: pip-lhapdf-looptools
    image: apnpucky/ubuntu-pip-lhapdf-looptools:${TAG:-latest}
