version: '3.4'
services:
  base:
    build:
      context: .
      target: base
    image: apnpucky/debian-base:${TAG:-latest}

  cmake-boost-gfortran:
    build:
      context: .
      target: cmake-boost-gfortran
    image: apnpucky/debian-cmake-boost-gfortran:${TAG:-latest}

  lhapdf:
    build:
      context: .
      target: lhapdf
    image: apnpucky/debian-lhapdf:${TAG:-latest}

  lhapdf-looptools:
    build:
      context: .
      target: lhapdf-looptools
    image: apnpucky/debian-lhapdf-looptools:${TAG:-latest}

#  looptools:
#    build:
#      context: .
#      target: looptools
#    image: apnpucky/docker-debian-looptools:${TAG:-latest}

  resummino-3.1.0:
    build:
      context: .
      target: resummino
      args:
        - RESUMMINO_VERSION=3.1.0
    image: apnpucky/resummino:3.1.0-${TAG:-latest}

  resummino-3.1.1:
    build:
      context: .
      target: resummino
      args:
        - RESUMMINO_VERSION=3.1.1
    image: apnpucky/resummino:3.1.1-${TAG:-latest}

  resummino-3.1.2:
    build:
      context: .
      target: resummino
      args:
        - RESUMMINO_VERSION=3.1.2
    image: apnpucky/resummino:3.1.2-${TAG:-latest}

  resummino:
    build:
      context: .
      target: resummino
    image: apnpucky/resummino:${TAG:-latest}

  latexmk:
    build:
      context: .
      target: latexmk
    image: apnpucky/debian-latexmk:${TAG:-latest}
