version: '3.4'
services:
  lhapdf:
    build:
      context: .
      target: gentoo-lhapdf
    image: apnpucky/gentoo-lhapdf:${TAG:-latest}

  yoda:
    build:
      context: .
      target: gentoo-yoda
    image: apnpucky/gentoo-yoda:${TAG:-latest}

  lhapdf-looptools:
    build:
      context: .
      target: gentoo-lhapdf-looptools
    image: apnpucky/gentoo-lhapdf-looptools:${TAG:-latest}

  rivet3-pythia8-hepmc3:
    build:
      context: .
      target: gentoo-rivet3-pythia8-hepmc3
    image: apnpucky/gentoo-rivet3-pythia8-hepmc3:${TAG:-latest}

  rivet3-pythia8-hepmc2:
    build:
      context: .
      target: gentoo-rivet3-pythia8-hepmc2
    image: apnpucky/gentoo-rivet3-pythia8-hepmc2:${TAG:-latest}

  prefix:
    build:
      context: .
      target: prefix
    image: apnpucky/gentoo-prefix:${TAG:-latest}

  susy:
    build:
      context: .
      target: gentoo-susy
    image: apnpucky/gentoo-susy:${TAG:-latest}

  hepi:
    build:
      context: .
      target: gentoo-hepi
    image: apnpucky/gentoo-hepi:${TAG:-latest}

#  latex:
#    build:
#      context: .
#      target: gentoo-latex
#    image: apnpucky/gentoo-latex:${TAG:-latest}
