version: '3.4'
services:

  ########################################################
  # CENTOS BUILDS                                        #
  ########################################################

  centos:
    build:
      context: .
      target: centos-easybuild
    image: apnpucky/centos7-easybuild:${TAG:-latest}

  centos-GCC-8.2.0:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-8.2.0.eb
    image: apnpucky/centos7-easybuild:GCC-8.2.0-${TAG:-latest}

  centos-GCC-9.3.0:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-9.3.0.eb
    image: apnpucky/centos7-easybuild:GCC-9.3.0-${TAG:-latest}

  centos-GCC-10.3.0:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-10.3.0.eb
    image: apnpucky/centos7-easybuild:GCC-10.3.0-${TAG:-latest}

  centos-GCC-11.3.0:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-11.3.0.eb
    image: apnpucky/centos7-easybuild:GCC-11.3.0-${TAG:-latest}

  centos-gompi-2019a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-8.2.0.eb
        - EASYINSTALL2=gompi-2019a.eb
    image: apnpucky/centos7-easybuild:gompi-2019a-${TAG:-latest}

  centos-gompi-2020a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-9.3.0.eb
        - EASYINSTALL2=gompi-2020a.eb
    image: apnpucky/centos7-easybuild:gompi-2020a-${TAG:-latest}

  centos-gompi-2021a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-10.3.0.eb
        - EASYINSTALL2=gompi-2021a.eb
    image: apnpucky/centos7-easybuild:gompi-2021a-${TAG:-latest}

  centos-gompi-2022a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-11.3.0.eb
        - EASYINSTALL2=gompi-2022a.eb
    image: apnpucky/centos7-easybuild:gompi-2022a-${TAG:-latest}

  centos-foss-2019a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-8.2.0.eb
        - EASYINSTALL2=gompi-2019a.eb
        - EASYINSTALL3=foss-2019a.eb
    image: apnpucky/centos7-easybuild:foss-2019a-${TAG:-latest}

  centos-foss-2020a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-9.3.0.eb
        - EASYINSTALL2=gompi-2020a.eb
        - EASYINSTALL3=foss-2020a.eb
    image: apnpucky/centos7-easybuild:foss-2020a-${TAG:-latest}

  centos-foss-2021a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-10.3.0.eb
        - EASYINSTALL2=gompi-2021a.eb
        - EASYINSTALL3=foss-2021a.eb
    image: apnpucky/centos7-easybuild:foss-2021a-${TAG:-latest}

  centos-foss-2022a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYINSTALL1=GCCcore-11.3.0.eb
        - EASYINSTALL2=gompi-2022a.eb
        - EASYINSTALL3=foss-2022a.eb
    image: apnpucky/centos7-easybuild:foss-2022a-${TAG:-latest}
  ########################################################
  # GENTOO BUILDS                                        #
  ########################################################

  #  easybuild-GCC-11.2.0:
  #    build:
  #      context: .
  #      target: gentoo-easybuild
  #      args:
  #        - EASYCONFIG=GCC-11.2.0.eb
  #    image: apnpucky/gentoo-easybuild:GCC-11.2.0-${TAG:-latest}
  #
  #  easybuild-foss-2019a:
  #    build:
  #      context: .
  #      target: gentoo-easybuild
  #      args:
  #        - EASYCONFIG=foss-2019a.eb
  #    image: apnpucky/gentoo-easybuild:foss-2019a-${TAG:-latest}
  #
  #  easybuild-foss-2020a:
  #    build:
  #      context: .
  #      target: gentoo-easybuild
  #      args:
  #        - EASYCONFIG=foss-2020a.eb
  #    image: apnpucky/gentoo-easybuild:foss-2020a-${TAG:-latest}
  #
  #  easybuild-foss-2022a:
  #    build:
  #      context: .
  #      target: gentoo-easybuild
  #      args:
  #        - EASYCONFIG=foss-2022a.eb
  #    image: apnpucky/gentoo-easybuild:foss-2022a-${TAG:-latest}
  #
  ##  easybuild-gompi-2022a:
  ##    build:
  ##      context: .
  ##      target: gentoo-easybuild
  ##      args:
  ##        - EASYCONFIG=gompi-20202.eb
  ##    image: apnpucky/gentoo-easybuild:gompi-2022a-${TAG:-latest}
