version: '3.4'
services:

  ########################################################
  # CENTOS BUILDS                                        #
  ########################################################

#  centos-foss-2020a:
#    build:
#      context: .
#      target: centos-easybuild-foss-2020a
#    image: apnpucky/centos-easybuild-foss-2020a:${TAG:-latest}
#
#  centos-foss-2020a-Boost-1.72.0:
#    build:
#      context: .
#      target: centos-easybuild-foss-2020a-x
#      args:
#        - EASYINSTALL=Boost-1.72.0-gompi-2020a.eb
#    image: apnpucky/centos-easybuild-foss-2020a:Boost-1.72.0-${TAG:-latest}

  centos:
    build:
      context: .
      target: centos-easybuild
    image: apnpucky/centos-easybuild:${TAG:-latest}

  centos-GCC-11.2.0:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYCONFIG=GCC-11.2.0.eb
    image: apnpucky/centos-easybuild:GCC-11.2.0-${TAG:-latest}

  centos-foss-2019a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYCONFIG=foss-2019a.eb
    image: apnpucky/centos-easybuild:foss-2019a-${TAG:-latest}

  centos-foss-2020a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYCONFIG=foss-2020a.eb
    image: apnpucky/centos-easybuild:foss-2020a-${TAG:-latest}

  centos-foss-2021a:
    build:
      context: .
      target: centos-easybuild
      args:
        - EASYCONFIG=foss-2020a.eb
    image: apnpucky/centos-easybuild:foss-2020a-${TAG:-latest}

  ########################################################
  # GENTOO BUILDS                                        #
  ########################################################

#  easybuild-GCC-11.2.0:
#    build:
#      context: .
#      target: gentoo-easybuild
#      args:
#        - EASYCONFIG=GCC-11.2.0.eb
#    image: apnpucky/gentoo-easybuild:GCC-11.2.0-${TAG:-latest}
#
#  easybuild-foss-2019a:
#    build:
#      context: .
#      target: gentoo-easybuild
#      args:
#        - EASYCONFIG=foss-2019a.eb
#    image: apnpucky/gentoo-easybuild:foss-2019a-${TAG:-latest}
#
#  easybuild-foss-2020a:
#    build:
#      context: .
#      target: gentoo-easybuild
#      args:
#        - EASYCONFIG=foss-2020a.eb
#    image: apnpucky/gentoo-easybuild:foss-2020a-${TAG:-latest}
#
#  easybuild-foss-2022a:
#    build:
#      context: .
#      target: gentoo-easybuild
#      args:
#        - EASYCONFIG=foss-2022a.eb
#    image: apnpucky/gentoo-easybuild:foss-2022a-${TAG:-latest}
#
##  easybuild-gompi-2022a:
##    build:
##      context: .
##      target: gentoo-easybuild
##      args:
##        - EASYCONFIG=gompi-20202.eb
##    image: apnpucky/gentoo-easybuild:gompi-2022a-${TAG:-latest}
