name: Debian Docker Image CI



on:
  push:
    branches: [ "master" ]
    paths:
      - gentoo/Dockerfile

jobs:
  docker:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        user: ["apnpucky"]
        base: [ "gentoo" ]
        image: ["base", "repo","ebuild-ci","dev","hep-forge","lhapdf-looptools","rivet3-pythia8-hepmc3","rivet3-pythia8-hepmc2"]
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDDHHSS
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: ${{ matrix.base }}-${{ matrix.image }}
        uses: docker/build-push-action@v3
        with:
          file: gentoo/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          push: true
          target: ${{ matrix.base }}-${{ matrix.image }}
          tags: |
            ${{ matrix.user }}/${{ matrix.base }}-${{ matrix.image }}:latest
            ${{ matrix.user }}/${{ matrix.base }}-${{ matrix.image }}:${{ github.sha }}-latest
            ${{ matrix.user }}/${{ matrix.base }}-${{ matrix.image }}:${{ steps.current-time.outputs.formattedTime }}-latest
