name: Debian Docker Image CI



on:
  push:
    branches: [ "master" ]
    paths:
      - gentoo/Dockerfile

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDDHHSS
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: gentoo-base
        uses: docker/build-push-action@v3
        with:
          file: gentoo/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          push: true
          target: gentoo-base
          tags: |
            apnpucky/gentoo-base:latest
            apnpucky/gentoo-base:${{ github.sha }}-latest
            apnpucky/gentoo-base:${{ steps.current-time.outputs.formattedTime }}-latest
      -
        name: gentoo-repo
        uses: docker/build-push-action@v3
        with:
          file: gentoo/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          push: true
          target: gentoo-repo
          tags: |
            apnpucky/gentoo-repo:latest
            apnpucky/gentoo-repo:${{ github.sha }}-latest
            apnpucky/gentoo-repo:${{ steps.current-time.outputs.formattedTime }}-latest
      