name: Ubuntu Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - ubuntu/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDDHHSS
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          target: apt
          tags: |
            apnpucky/ubuntu-apt:latest
            apnpucky/ubuntu-apt:${{ github.sha }}-latest
            apnpucky/ubuntu-apt:${{ steps.current-time.outputs.formattedTime }}-latest
